{% set name = "simdjson" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/simdjson/simdjson/archive/{{ version }}.tar.gz
  sha256: 14d17ba7139d27c1e1bf01e765f5c26e84cc9e9be6a316c977638e01c7de85fa

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - simdjson

requirements:
  build:
    - {{ compiler('cxx') }}

test:
  commands:
    - test -f $PREFIX/include/simdjson.h
    - test -f $PREFIX/lib/libsimdjson.so

about:
  home: https://github.com/simdjson/simdjson
  license: Apache-2.0
  license_file: LICENSE
  summary: Parsing gigabytes of JSON per second

  description: |
    JSON is everywhere on the Internet.
    Servers spend a *lot* of time parsing it. We need a fresh approach.
    The simdjson library uses commonly available SIMD instructions and
    microparallel algorithms to parse JSON 2.5x faster than anything else out there.
  doc_url: https://github.com/simdjson/simdjson#quick-start
  dev_url: https://github.com/simdjson/simdjson

extra:
  recipe-maintainers:
    - elbaro
